version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container's port 3000 to the host's port 3000
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
